#error_on_line_overflow = true
#error_on_unformatted = true
#
## Run rustfmt with this config (it should be picked up automatically).
#version = "Two"
#use_small_heuristics = "Max"
#merge_derives = false
#
## by default we ignore everything in the repository
## tidy only checks files which are not ignored, each entry follows gitignore style
#ignore = [
#    # do not format submodules
#    "/build/",
#    "/*-build/",
#    "/build-*/",
#    "/vendor/",
#
#    # tests for now are not formatted, as they are sometimes pretty-printing constrained
#    # (and generally rustfmt can move around comments in UI-testing incompatible ways)
#    "src/test",
#]
